---
abstract: 'Titlecase English words by traditional editorial rules.'
author:
  - 'Ashley Pond V  C<< <ashley@cpan.org> >>.'
build_requires:
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.75'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Lingua-EN-Titlecase
no_index:
  directory:
    - inc
    - t
requires:
  Carp: 0
  Class::Accessor::Fast: 0
  HTML::TokeParser: 2
  List::Util: 0
  parent: 0.2
  perl: 5.6.0
version: 0.11
